// site-react/src/components/categories/Article.jsx
import React, { useState, useEffect } from 'react'
import axios from 'axios'

import PageTitle from '../templates/pageTitle/PageTitle'
import { articleUrl } from '../../global'

import './Article.css'

export default function Article(props) {
    const articleId = props.match.params.id
    const [article, setArticle] = useState(null)
    useEffect(() => {
        if (!article) {
            loadArticle(articleId)
                .then(res => setArticle({ ...res.data }))
        }
    })

    const articleContent = article ? article.content : ''
    return (
        <div>
            <PageTitle
                icon="fa fa-file-o"
                title={article ? article.name : ''}
                subTitle={article ? article.description : ''}
            />
            <div className="article" dangerouslySetInnerHTML={{ __html: articleContent }}>
            </div>
        </div >
    )
}

function loadArticle(id) {
    return axios.get(`${articleUrl}/${id}`)
}

// site-vue/src/components/articles/Article.vue
<template>
  <div>
    <PageTitle :title="article.name" :subTitle="article.description" icon="fa fa-file-o" />
    <div class="article-content" v-html="article.content"></div>
  </div>
</template>

<script>
import PageTitle from "../templates/PageTitle";
import { showError, articlesUrl } from "@/global";
import axios from "axios";
export default {
  name: "Article",
  components: { PageTitle },
  data() {
    return {
      article: {}
    };
  },
  methods: {
    loadArticle(id) {
      axios
        .get(`${articlesUrl}/${id}`)
        .then(res => {
          this.article = res.data;
        })
        .catch(showError);
    }
  },
  mounted() {
    this.loadArticle(this.$route.params.id);
  }
};
</script>
<style>
.article-content {
    background-color: #FFF;
    border-radius: 8px;
    padding: 25px;
}
</style>
