// site-vue/src/components/admin/AdminPage.vue
<template>
  <div class="admin-page">
    <PageTitle icon="fa fa-cogs" title=" Administração do Sistema" subTitle="Cadastros & Cia" />
    <div class="tabs">
      <b-card no-body>
        <b-tabs card>
          <b-tab title="Artigos" active>
              <ArticleAdmin />
          </b-tab>
          <b-tab title="Categorias">
            <CategoryAdmin />
          </b-tab>
          <b-tab title="Usuários">
              <UserAdmin />
          </b-tab>
        </b-tabs>
      </b-card>
    </div>
  </div>
</template>

<script>
import PageTitle from "../templates/PageTitle"
import CategoryAdmin from './CategoryAdmin'
import ArticleAdmin from './ArticleAdmin'
import UserAdmin from './UserAdmin'
export default {
  name: "AdminPage",
  components: { PageTitle, CategoryAdmin, ArticleAdmin, UserAdmin }
};
</script>

<style>
</style>

// site-react/src/components/admin/AdminPage.jsx
import React, { Component } from 'react'
import PageTitle from '../templates/pageTitle/PageTitle'
import Tab from '../templates/tab/Tab'

import AdminArticles from './AdminArticles'
import AdminCategories from './AdminCategories'
import AdminUsers from './AdminUsers'

import './AdminPage.css'

export default class AdminPage extends Component {

    constructor(props) {
        super(props)
        this.state = { activeContentId: '' }
    }

    render() {
        return (
            <div className="admin-page">
                <PageTitle title="Administração do Sistema" subTitle="Cadastros & Cia" icon="fa fa-cogs" />
                <div className="admin-page-tabs">
                    <Tab>
                        <Tab.Item id="1" active title="Artigos">
                            <AdminArticles />
                        </Tab.Item>
                        <Tab.Item id="2" title="Categorias">
                            <AdminCategories />
                        </Tab.Item>
                        <Tab.Item id="3" title="Usuários">
                            <AdminUsers />
                        </Tab.Item>
                    </Tab>
                </div>
            </div>
        )
    }
}
